language: python
python:
  - "3.3"
# command to install dependencies
install:
  - python setup.py sdist --formats=zip -k
  - find ./dist -iname "*.zip" -print0 | xargs -0 pip install
  - mkdir ./tests/slpp_tests
  - cp ./Travis/* ./tests/slpp_tests
  - cd ./tests/slpp_tests
  - wget https://googledrive.com/host/0B5wKXY68Wip5S3IwN2xqaGMyY1U/DRAGONs_AttackOnKrymsk_V78.miz
  - wget https://googledrive.com/host/0B5wKXY68Wip5S3IwN2xqaGMyY1U/DRAGONs_BlackGoldOfAnapa_V78.miz
  - wget https://googledrive.com/host/0B5wKXY68Wip5S3IwN2xqaGMyY1U/DRAGONs_Convoyhunting_V78.miz
  - wget https://googledrive.com/host/0B5wKXY68Wip5S3IwN2xqaGMyY1U/DRAGONs_DefenseOfBatumi_V78.miz
  - wget https://googledrive.com/host/0B5wKXY68Wip5S3IwN2xqaGMyY1U/DRAGONs_DefenseOfGelendzhik_V78.miz
  - wget https://googledrive.com/host/0B5wKXY68Wip5S3IwN2xqaGMyY1U/DRAGONs_GudautaRush_V78.miz
  - wget https://googledrive.com/host/0B5wKXY68Wip5S3IwN2xqaGMyY1U/DRAGONs_HamburgerHill_V78.miz
  - wget https://googledrive.com/host/0B5wKXY68Wip5S3IwN2xqaGMyY1U/DRAGONs_HardcoreTerrorists_V78.miz
  - wget https://googledrive.com/host/0B5wKXY68Wip5S3IwN2xqaGMyY1U/DRAGONs_NightHawkHunter_V78.miz
  - wget https://googledrive.com/host/0B5wKXY68Wip5S3IwN2xqaGMyY1U/DRAGONs_OperationBigfoot_V78.miz
  - wget https://googledrive.com/host/0B5wKXY68Wip5S3IwN2xqaGMyY1U/DRAGONs_OperationBunnyEscort_V78.miz
  - wget https://googledrive.com/host/0B5wKXY68Wip5S3IwN2xqaGMyY1U/DRAGONs_OperationPushBack_V78.miz
  - cd ../../tests
# command to run tests
script: nosetests
# - python tdcmeme-0.0.1/tests.py
branches:
  only:
    - master
    - /^deploy-.*$/