#This file was originally generated by PyScripter's unitest wizard

import unittest
import main
import _slpp
import os

class TestGlobalFunctions(unittest.TestCase):

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testSLPP(self):
        file_in = os.path.join(os.getcwd(),r"slpp tests\mission")
        file_out = os.path.join(os.getcwd(),r"slpp tests\output")
        p = _slpp.SLPP()
        with open(file_out, mode="w", encoding="UTF-8") as _out:
            with open(file_in, encoding="UTF-8") as _in:
                dict_in = p.decode(_in.read())
                _out.write(p.encode(dict_in))

        with open(file_out, mode="r", encoding="UTF-8") as _out:
            dict_out = p.decode(_out.read())
        self.assertTrue(dict_in == dict_out)



if __name__ == '__main__':
    unittest.main()
