#This file was originally generated by PyScripter's unitest wizard

import unittest
import main
import _slpp
import os

class TestGlobalFunctions(unittest.TestCase):

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testSLPP(self):
        '''
        Verifies that the SLPP parser outputs the EXACT same output, providing
        the mission file has not been changed

        Fixes gh-1
        '''
        file_in = os.path.join(os.getcwd(),r"slpp tests\mission")
        file_out = os.path.join(os.getcwd(),r"slpp tests\output")
        p = _slpp.SLPP()
        with open(file_out, mode="w", encoding="UTF-8") as _out:
            with open(file_in, encoding="UTF-8") as _in:
                _out.write(p.encode(p.decode(_in.read())))
        self.assertTrue(open(file_in).read() == open(file_out).read())



if __name__ == '__main__':
    unittest.main()
